name: Test resumel templates

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-full \
          latexmk \
          diff-pdf \
          emacs

    - name: Install Emacs packages
      run: |
        emacs --batch --eval "(package-refresh-contents)"
        emacs --batch --eval "(package-install 'org)"
        emacs --batch --eval "(package-install 'ox-extra)"

    - name: Run tests
      run: |
        make test

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: tests/results
