name: Test resumel templates

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEXMFHOME: ${{ github.workspace }}/texmf
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            latexmk \
            emacs \
            make \
            curl \
            automake \
            g++ \
            libpoppler-glib-dev \
            poppler-utils \
            git

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3.4.1
        with:
          packages: |
            latexmk
            xetex
            scheme-basic
            moderncv
            paracol
            etoolbox
            lmodern
            inputenc
            fontenc
            geometry
            xcolor
            tikz
            tikzfill
            amsmath
            amsfonts
            fontawesome5
            hyperref
            biblatex
            biblatex-ieee
            pdfpages
            titlesec
            pdfcomment
            fancyhdr
            enumitem
            csquotes
            pdflscape
            roboto
            lato
            footmisc
            unicode-math
            multibib
            babel
            ifxetex
            ifluatex
            luatextra
            lualatex-math
            shellesc
            inputenx
            fontenc
            txfonts
            marvosym
            pifont
            parskip
            graphicx
            graphics
            caption
            marvosym
            latexsym
            url
            xspace
            mparhack
            microtype
            multicol
            listings
            dashrule
            ifmtarg
            newtxmath
            extsizes
            pdfx
            accsupp
            scrhack
            koma-script
            xparse
            everyshi
            xmpincl
            iftex
            fontspec
            ragged2e
            pgf
            trig
            tcolorbox
            verbatim
            environ
            trimspaces
            l3kernel
            l3packages
            adjustbox
            collectbox
            xkeyval
            multirow
            tools
            changepage
            logreq
            base
            kvsetkeys
            kvdefinekeys
            pdfescape
            ltxcmds
            pdftexcmds
            infwarerr
            hycolor
            auxhook
            refcount
            gettitlestring
            kvoptions
            intcalc
            bitset
            bigintcalc
            stringenc
            rerunfilecheck
            uniquecounter
            colorprofiles
            cmap
            wrapfig
            fontaxes
            ulem
            capt-of
            array
            xifthen
            xstring
            setspace
            sourcesanspro
            bookmark

      - name: Clone AltaCV Repository
        run: |
          mkdir -p $TEXMFHOME/tex/latex
          git clone https://github.com/liantze/AltaCV.git $TEXMFHOME/tex/latex/altacv

      - name: Clone AwesomeCV Repository
        run: |
          mkdir -p $TEXMFHOME/tex/latex
          git clone https://github.com/posquit0/Awesome-CV.git $TEXMFHOME/tex/latex/awesomecv

      - name: Refresh TeX Live Filename Database
        run: |
          mktexlsr $TEXMFHOME

      - name: Setup Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install diff-pdf via Homebrew
        run: |
          brew install diff-pdf

      - name: Debug CI Emacs Setup
        run: |
          echo "Listing Emacs version info:"
          emacs --version
          echo "Listing Emacs Org version info:"
          emacs --batch -l ./test-init.el --eval '(princ (org-version))' --kill
          echo "Listing pdflatex version info:"
          pdflatex --version
          echo "Listing xetex version info:"
          xetex --version
          echo "TEXMFHOME is set to: $TEXMFHOME"
          echo "Listing contents of $TEXMFHOME/tex/latex/altacv:"
          ls -la $TEXMFHOME/tex/latex/altacv
          echo "Listing contents of $TEXMFHOME/tex/latex/awesomecv:"
          ls -la $TEXMFHOME/tex/latex/awesomecv

      - name: Run tests
        env:
          EMACS_FLAGS: "--batch -l ./test-init.el"
        run: |
          make test EMACS=emacs EMACS_FLAGS="${EMACS_FLAGS}"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/results
