name: Test resumel templates

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Define a separate Emacs user directory for CI
      USER_EMACS_DIR: ${{ github.workspace }}/ci_emacs.d
      # Set TEXMFHOME to a directory within the workspace
      TEXMFHOME: ${{ github.workspace }}/texmf
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          latexmk \
          emacs \
          make \
          curl \
          automake \
          g++ \
          libpoppler-glib-dev \
          poppler-utils \
          libwxgtk3.2-dev \
          git

    - name: Set up TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: |
          scheme-basic
          moderncv
          paracol
          etoolbox
          lmodern
          inputenc
          fontenc
          geometry
          xcolor
          tikz
          tikzfill
          amsmath
          amsfonts
          fontawesome5
          hyperref
          biblatex
          biblatex-ieee
          pdfpages
          titlesec
          pdfcomment
          fancyhdr
          enumitem
          csquotes
          pdflscape
          roboto
          lato
          footmisc
          unicode-math
          multibib
          babel
          ifxetex
          ifluatex
          luatextra
          lualatex-math
          shellesc
          inputenx
          fontenc
          txfonts
          marvosym
          pifont
          parskip
          graphicx
          graphics
          caption
          marvosym
          latexsym
          url
          xspace
          mparhack
          microtype
          multicol
          listings
          dashrule
          ifmtarg
          newtxmath
          extsizes
          pdfx
          accsupp
          scrhack
          koma-script
          xparse
          everyshi
          xmpincl
          iftex
          fontspec
          ragged2e
          pgf
          trig
          tcolorbox
          verbatim
          environ
          trimspaces
          l3kernel
          l3packages
          adjustbox
          collectbox
          xkeyval
          multirow
          tools
          changepage
          logreq
          base
          kvsetkeys
          kvdefinekeys
          pdfescape
          ltxcmds
          pdftexcmds
          infwarerr
          hycolor
          auxhook
          refcount
          gettitlestring
          kvoptions
          intcalc
          bitset
          bigintcalc
          stringenc
          rerunfilecheck
          uniquecounter
          colorprofiles
          cmap
          wrapfig
          fontaxes
          ulem

    - name: Clone AltaCV Repository
      run: |
        mkdir -p $TEXMFHOME/tex/latex
        git clone https://github.com/liantze/AltaCV.git $TEXMFHOME/tex/latex/altacv

    - name: Refresh TeX Live Filename Database
      run: |
        mktexlsr $TEXMFHOME

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install diff-pdf via Homebrew
      run: |
        brew install diff-pdf

    - name: Setup Emacs for CI
      run: |
        mkdir -p $USER_EMACS_DIR/lisp
        echo "(setq user-emacs-directory \"${USER_EMACS_DIR}\")" > $USER_EMACS_DIR/init.el
        echo "(require 'package)" >> $USER_EMACS_DIR/init.el
        echo "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" >> $USER_EMACS_DIR/init.el
        echo "(add-to-list 'package-archives '(\"gnu\" . \"https://elpa.gnu.org/packages/\") t)" >> $USER_EMACS_DIR/init.el
        echo "(add-to-list 'package-archives '(\"org\" . \"https://orgmode.org/elpa/\") t)" >> $USER_EMACS_DIR/init.el
        echo "(add-to-list 'package-archives '(\"org-contrib\" . \"https://orgmode.org/elpa/\") t)" >> $USER_EMACS_DIR/init.el
        echo "(package-initialize)" >> $USER_EMACS_DIR/init.el
        echo "(unless package-archive-contents (package-refresh-contents))" >> $USER_EMACS_DIR/init.el
        echo "(package-install 'org)" >> $USER_EMACS_DIR/init.el
        echo "(package-install 'org-contrib)" >> $USER_EMACS_DIR/init.el
        echo "(require 'ox-extra)" >> $USER_EMACS_DIR/init.el
        echo "(setq max-lisp-eval-depth 2000)" >> $USER_EMACS_DIR/init.el
        echo "(setq max-specpdl-size 15000)" >> $USER_EMACS_DIR/init.el
        echo "(ox-extras-activate '(ignore-headlines))" >> $USER_EMACS_DIR/init.el

    - name: Debug CI Emacs Setup
      run: |
        echo "USER_EMACS_DIR is set to: $USER_EMACS_DIR"
        echo "TEXMFHOME is set to: $TEXMFHOME"
        echo "Listing contents of $USER_EMACS_DIR:"
        ls -la $USER_EMACS_DIR
        echo "Listing contents of $TEXMFHOME/tex/latex/altacv:"
        ls -la $TEXMFHOME/tex/latex/altacv

    - name: Run tests
      env:
        # Set Emacs to use the CI-specific user directory
        EMACS_FLAGS: "--batch -l ${USER_EMACS_DIR}/init.el"
        # Disable package installation in Makefile since packages are already installed
        LOAD_EMACS_PACKAGES: "false"
      run: |
        make test EMACS=emacs EMACS_FLAGS="${EMACS_FLAGS}" LOAD_EMACS_PACKAGES="false"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/results
